// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/protocol/user.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequest_Provider int32

const (
	CreateUserRequest_Google CreateUserRequest_Provider = 0
)

var CreateUserRequest_Provider_name = map[int32]string{
	0: "Google",
}

var CreateUserRequest_Provider_value = map[string]int32{
	"Google": 0,
}

func (x CreateUserRequest_Provider) String() string {
	return proto.EnumName(CreateUserRequest_Provider_name, int32(x))
}

func (CreateUserRequest_Provider) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e4f7598aa02a15e, []int{0, 0}
}

type CreateUserRequest struct {
	Id                   string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider             CreateUserRequest_Provider `protobuf:"varint,2,opt,name=provider,proto3,enum=egommerce.user.CreateUserRequest_Provider" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4f7598aa02a15e, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateUserRequest) GetProvider() CreateUserRequest_Provider {
	if m != nil {
		return m.Provider
	}
	return CreateUserRequest_Google
}

type UserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4f7598aa02a15e, []int{1}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4f7598aa02a15e, []int{2}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4f7598aa02a15e, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterEnum("egommerce.user.CreateUserRequest_Provider", CreateUserRequest_Provider_name, CreateUserRequest_Provider_value)
	proto.RegisterType((*CreateUserRequest)(nil), "egommerce.user.CreateUserRequest")
	proto.RegisterType((*UserRequest)(nil), "egommerce.user.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "egommerce.user.UserResponse")
	proto.RegisterType((*User)(nil), "egommerce.user.User")
}

func init() { proto.RegisterFile("pkg/protocol/user.proto", fileDescriptor_8e4f7598aa02a15e) }

var fileDescriptor_8e4f7598aa02a15e = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x35, 0x31, 0x86, 0x74, 0x2a, 0x41, 0x87, 0xa2, 0x41, 0x14, 0xea, 0x9e, 0x82, 0x87, 0x2d,
	0xc4, 0x8b, 0x47, 0x51, 0x50, 0xbc, 0x49, 0x44, 0x10, 0x6f, 0x31, 0x19, 0xc2, 0x62, 0xd2, 0x8d,
	0xbb, 0x69, 0x7f, 0xc0, 0x1f, 0x97, 0xcc, 0xb6, 0x82, 0x56, 0xec, 0x6d, 0xde, 0xdb, 0x37, 0x33,
	0xef, 0xed, 0xc0, 0x71, 0xf7, 0x5e, 0xcf, 0x3a, 0xa3, 0x7b, 0x5d, 0xea, 0x66, 0xb6, 0xb0, 0x64,
	0x24, 0x23, 0x8c, 0xa9, 0xd6, 0x6d, 0x4b, 0xa6, 0x24, 0x39, 0xb0, 0xe2, 0xd3, 0x83, 0xc3, 0x5b,
	0x43, 0x45, 0x4f, 0xcf, 0x96, 0x4c, 0x4e, 0x1f, 0x0b, 0xb2, 0x3d, 0xc6, 0xe0, 0xab, 0x2a, 0xf1,
	0xa6, 0x5e, 0x3a, 0xca, 0x7d, 0x55, 0xe1, 0x1d, 0x44, 0x9d, 0xd1, 0x4b, 0x55, 0x91, 0x49, 0xfc,
	0xa9, 0x97, 0xc6, 0xd9, 0x85, 0xfc, 0x39, 0x48, 0x6e, 0x0c, 0x91, 0x8f, 0xab, 0x8e, 0xfc, 0xbb,
	0x57, 0x1c, 0x41, 0xb4, 0x66, 0x11, 0x20, 0xbc, 0xd7, 0xba, 0x6e, 0xe8, 0x60, 0x47, 0x9c, 0xc1,
	0xf8, 0x9f, 0xf5, 0xe2, 0x0a, 0xf6, 0xdd, 0xb3, 0xed, 0xf4, 0xdc, 0x12, 0xa6, 0x10, 0x0c, 0x3b,
	0x59, 0x31, 0xce, 0x26, 0xbf, 0xad, 0xb0, 0x96, 0x15, 0xe2, 0x1a, 0x82, 0x01, 0x6d, 0x04, 0x42,
	0x08, 0xe6, 0x45, 0x4b, 0x1c, 0x66, 0x94, 0x73, 0x8d, 0x13, 0xd8, 0xa3, 0xb6, 0x50, 0x4d, 0xb2,
	0xcb, 0xa4, 0x03, 0xd9, 0x8b, 0xb3, 0xf6, 0x44, 0x66, 0xa9, 0x4a, 0xc2, 0x07, 0x08, 0x5d, 0x52,
	0x3c, 0xdf, 0xfa, 0x03, 0x27, 0xa7, 0x7f, 0x3a, 0x5b, 0xa5, 0xb8, 0x81, 0xd7, 0x68, 0x7d, 0xa1,
	0xb7, 0x90, 0xab, 0xcb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x2b, 0x81, 0x92, 0xb8, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/egommerce.user.UserService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Create(context.Context, *CreateUserRequest) (*UserResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Create(ctx context.Context, req *CreateUserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/egommerce.user.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "egommerce.user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/protocol/user.proto",
}
